services:
  comp3123-frontend:
    image: ghcr.io/gbc-ekos/comp3123-frontend:latest
    container_name: comp3123-frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.comp3123-frontend.rule=Host(`comp3123-frontend.ekosenko.me`)
      - traefik.http.routers.comp3123-frontend.entrypoints=websecure
      - traefik.http.routers.comp3123-frontend.tls.certresolver=le
      - traefik.http.routers.comp3123-frontend-http.rule=Host(`comp3123-frontend.ekosenko.me`)
      - traefik.http.routers.comp3123-frontend-http.entrypoints=web
      - traefik.http.routers.comp3123-frontend-http.middlewares=to-https
      - traefik.http.middlewares.to-https.redirectscheme.scheme=https
      - traefik.http.services.comp3123-frontend.loadbalancer.server.port=3000

networks:
  traefik:
    external: true